// Package clusterpb defines the internal codeq-to-codeq protocol. External
// (producer/worker) clients still speak REST; this gRPC surface is only
// reachable on the cluster network.
//
// Service shape:
//   - Operations that know a task ID (Get/Heartbeat/Result/Nack/Abandon)
//     route directly via consistent hash on the ID.
//   - Operations that do NOT know a task ID (LocalClaim, PendingLength,
//     AdminQueues) target a specific node by ID and act on that node's
//     local shard only — the caller is responsible for scatter-gather.
//   - BloomSnapshot returns the latest bloom of IDs durably stored on the
//     responding node. Routers query peer blooms to short-circuit
//     scatter-gather and outright-404 unknown IDs.
//
// Wire types: we keep this intentionally minimal. JSON-friendly fields
// (task payload, result body) travel as bytes/strings — encoding lives
// on the codeq side so we don't bake JSON shape choices into the proto.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: clusterpb.proto

package clusterpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskNode_Enqueue_FullMethodName          = "/clusterpb.TaskNode/Enqueue"
	TaskNode_GetTask_FullMethodName          = "/clusterpb.TaskNode/GetTask"
	TaskNode_Heartbeat_FullMethodName        = "/clusterpb.TaskNode/Heartbeat"
	TaskNode_Abandon_FullMethodName          = "/clusterpb.TaskNode/Abandon"
	TaskNode_Nack_FullMethodName             = "/clusterpb.TaskNode/Nack"
	TaskNode_SaveResult_FullMethodName       = "/clusterpb.TaskNode/SaveResult"
	TaskNode_UpdateOnComplete_FullMethodName = "/clusterpb.TaskNode/UpdateOnComplete"
	TaskNode_LocalClaim_FullMethodName       = "/clusterpb.TaskNode/LocalClaim"
	TaskNode_PendingLength_FullMethodName    = "/clusterpb.TaskNode/PendingLength"
	TaskNode_QueueStats_FullMethodName       = "/clusterpb.TaskNode/QueueStats"
	TaskNode_AdminQueues_FullMethodName      = "/clusterpb.TaskNode/AdminQueues"
	TaskNode_BloomSnapshot_FullMethodName    = "/clusterpb.TaskNode/BloomSnapshot"
)

// TaskNodeClient is the client API for TaskNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskNodeClient interface {
	// ID-routed (caller resolves owner via hash):
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	Abandon(ctx context.Context, in *AbandonRequest, opts ...grpc.CallOption) (*AbandonResponse, error)
	Nack(ctx context.Context, in *NackRequest, opts ...grpc.CallOption) (*NackResponse, error)
	SaveResult(ctx context.Context, in *SaveResultRequest, opts ...grpc.CallOption) (*SaveResultResponse, error)
	UpdateOnComplete(ctx context.Context, in *UpdateOnCompleteRequest, opts ...grpc.CallOption) (*UpdateOnCompleteResponse, error)
	// Scatter-gather (caller broadcasts to every node):
	LocalClaim(ctx context.Context, in *LocalClaimRequest, opts ...grpc.CallOption) (*LocalClaimResponse, error)
	PendingLength(ctx context.Context, in *PendingLengthRequest, opts ...grpc.CallOption) (*PendingLengthResponse, error)
	QueueStats(ctx context.Context, in *QueueStatsRequest, opts ...grpc.CallOption) (*QueueStatsResponse, error)
	AdminQueues(ctx context.Context, in *AdminQueuesRequest, opts ...grpc.CallOption) (*AdminQueuesResponse, error)
	// Bloom gossip (poll-style; a streaming version can be added later):
	BloomSnapshot(ctx context.Context, in *BloomSnapshotRequest, opts ...grpc.CallOption) (*BloomSnapshotResponse, error)
}

type taskNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskNodeClient(cc grpc.ClientConnInterface) TaskNodeClient {
	return &taskNodeClient{cc}
}

func (c *taskNodeClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, TaskNode_Enqueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNodeClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, TaskNode_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNodeClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, TaskNode_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNodeClient) Abandon(ctx context.Context, in *AbandonRequest, opts ...grpc.CallOption) (*AbandonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonResponse)
	err := c.cc.Invoke(ctx, TaskNode_Abandon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNodeClient) Nack(ctx context.Context, in *NackRequest, opts ...grpc.CallOption) (*NackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NackResponse)
	err := c.cc.Invoke(ctx, TaskNode_Nack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNodeClient) SaveResult(ctx context.Context, in *SaveResultRequest, opts ...grpc.CallOption) (*SaveResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveResultResponse)
	err := c.cc.Invoke(ctx, TaskNode_SaveResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNodeClient) UpdateOnComplete(ctx context.Context, in *UpdateOnCompleteRequest, opts ...grpc.CallOption) (*UpdateOnCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOnCompleteResponse)
	err := c.cc.Invoke(ctx, TaskNode_UpdateOnComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNodeClient) LocalClaim(ctx context.Context, in *LocalClaimRequest, opts ...grpc.CallOption) (*LocalClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocalClaimResponse)
	err := c.cc.Invoke(ctx, TaskNode_LocalClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNodeClient) PendingLength(ctx context.Context, in *PendingLengthRequest, opts ...grpc.CallOption) (*PendingLengthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PendingLengthResponse)
	err := c.cc.Invoke(ctx, TaskNode_PendingLength_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNodeClient) QueueStats(ctx context.Context, in *QueueStatsRequest, opts ...grpc.CallOption) (*QueueStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueStatsResponse)
	err := c.cc.Invoke(ctx, TaskNode_QueueStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNodeClient) AdminQueues(ctx context.Context, in *AdminQueuesRequest, opts ...grpc.CallOption) (*AdminQueuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminQueuesResponse)
	err := c.cc.Invoke(ctx, TaskNode_AdminQueues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNodeClient) BloomSnapshot(ctx context.Context, in *BloomSnapshotRequest, opts ...grpc.CallOption) (*BloomSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BloomSnapshotResponse)
	err := c.cc.Invoke(ctx, TaskNode_BloomSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskNodeServer is the server API for TaskNode service.
// All implementations must embed UnimplementedTaskNodeServer
// for forward compatibility.
type TaskNodeServer interface {
	// ID-routed (caller resolves owner via hash):
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	Abandon(context.Context, *AbandonRequest) (*AbandonResponse, error)
	Nack(context.Context, *NackRequest) (*NackResponse, error)
	SaveResult(context.Context, *SaveResultRequest) (*SaveResultResponse, error)
	UpdateOnComplete(context.Context, *UpdateOnCompleteRequest) (*UpdateOnCompleteResponse, error)
	// Scatter-gather (caller broadcasts to every node):
	LocalClaim(context.Context, *LocalClaimRequest) (*LocalClaimResponse, error)
	PendingLength(context.Context, *PendingLengthRequest) (*PendingLengthResponse, error)
	QueueStats(context.Context, *QueueStatsRequest) (*QueueStatsResponse, error)
	AdminQueues(context.Context, *AdminQueuesRequest) (*AdminQueuesResponse, error)
	// Bloom gossip (poll-style; a streaming version can be added later):
	BloomSnapshot(context.Context, *BloomSnapshotRequest) (*BloomSnapshotResponse, error)
	mustEmbedUnimplementedTaskNodeServer()
}

// UnimplementedTaskNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskNodeServer struct{}

func (UnimplementedTaskNodeServer) Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedTaskNodeServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskNodeServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedTaskNodeServer) Abandon(context.Context, *AbandonRequest) (*AbandonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Abandon not implemented")
}
func (UnimplementedTaskNodeServer) Nack(context.Context, *NackRequest) (*NackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Nack not implemented")
}
func (UnimplementedTaskNodeServer) SaveResult(context.Context, *SaveResultRequest) (*SaveResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveResult not implemented")
}
func (UnimplementedTaskNodeServer) UpdateOnComplete(context.Context, *UpdateOnCompleteRequest) (*UpdateOnCompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOnComplete not implemented")
}
func (UnimplementedTaskNodeServer) LocalClaim(context.Context, *LocalClaimRequest) (*LocalClaimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LocalClaim not implemented")
}
func (UnimplementedTaskNodeServer) PendingLength(context.Context, *PendingLengthRequest) (*PendingLengthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PendingLength not implemented")
}
func (UnimplementedTaskNodeServer) QueueStats(context.Context, *QueueStatsRequest) (*QueueStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueueStats not implemented")
}
func (UnimplementedTaskNodeServer) AdminQueues(context.Context, *AdminQueuesRequest) (*AdminQueuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminQueues not implemented")
}
func (UnimplementedTaskNodeServer) BloomSnapshot(context.Context, *BloomSnapshotRequest) (*BloomSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BloomSnapshot not implemented")
}
func (UnimplementedTaskNodeServer) mustEmbedUnimplementedTaskNodeServer() {}
func (UnimplementedTaskNodeServer) testEmbeddedByValue()                  {}

// UnsafeTaskNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskNodeServer will
// result in compilation errors.
type UnsafeTaskNodeServer interface {
	mustEmbedUnimplementedTaskNodeServer()
}

func RegisterTaskNodeServer(s grpc.ServiceRegistrar, srv TaskNodeServer) {
	// If the following call panics, it indicates UnimplementedTaskNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskNode_ServiceDesc, srv)
}

func _TaskNode_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNodeServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNode_Enqueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNodeServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNode_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNodeServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNode_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNodeServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNode_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNodeServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNode_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNodeServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNode_Abandon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNodeServer).Abandon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNode_Abandon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNodeServer).Abandon(ctx, req.(*AbandonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNode_Nack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNodeServer).Nack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNode_Nack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNodeServer).Nack(ctx, req.(*NackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNode_SaveResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNodeServer).SaveResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNode_SaveResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNodeServer).SaveResult(ctx, req.(*SaveResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNode_UpdateOnComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOnCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNodeServer).UpdateOnComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNode_UpdateOnComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNodeServer).UpdateOnComplete(ctx, req.(*UpdateOnCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNode_LocalClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNodeServer).LocalClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNode_LocalClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNodeServer).LocalClaim(ctx, req.(*LocalClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNode_PendingLength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PendingLengthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNodeServer).PendingLength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNode_PendingLength_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNodeServer).PendingLength(ctx, req.(*PendingLengthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNode_QueueStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNodeServer).QueueStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNode_QueueStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNodeServer).QueueStats(ctx, req.(*QueueStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNode_AdminQueues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminQueuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNodeServer).AdminQueues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNode_AdminQueues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNodeServer).AdminQueues(ctx, req.(*AdminQueuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNode_BloomSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BloomSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNodeServer).BloomSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNode_BloomSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNodeServer).BloomSnapshot(ctx, req.(*BloomSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskNode_ServiceDesc is the grpc.ServiceDesc for TaskNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clusterpb.TaskNode",
	HandlerType: (*TaskNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enqueue",
			Handler:    _TaskNode_Enqueue_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskNode_GetTask_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _TaskNode_Heartbeat_Handler,
		},
		{
			MethodName: "Abandon",
			Handler:    _TaskNode_Abandon_Handler,
		},
		{
			MethodName: "Nack",
			Handler:    _TaskNode_Nack_Handler,
		},
		{
			MethodName: "SaveResult",
			Handler:    _TaskNode_SaveResult_Handler,
		},
		{
			MethodName: "UpdateOnComplete",
			Handler:    _TaskNode_UpdateOnComplete_Handler,
		},
		{
			MethodName: "LocalClaim",
			Handler:    _TaskNode_LocalClaim_Handler,
		},
		{
			MethodName: "PendingLength",
			Handler:    _TaskNode_PendingLength_Handler,
		},
		{
			MethodName: "QueueStats",
			Handler:    _TaskNode_QueueStats_Handler,
		},
		{
			MethodName: "AdminQueues",
			Handler:    _TaskNode_AdminQueues_Handler,
		},
		{
			MethodName: "BloomSnapshot",
			Handler:    _TaskNode_BloomSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clusterpb.proto",
}
