// Package clusterpb defines the internal codeq-to-codeq protocol. External
// (producer/worker) clients still speak REST; this gRPC surface is only
// reachable on the cluster network.
//
// Service shape:
//   - Operations that know a task ID (Get/Heartbeat/Result/Nack/Abandon)
//     route directly via consistent hash on the ID.
//   - Operations that do NOT know a task ID (LocalClaim, PendingLength,
//     AdminQueues) target a specific node by ID and act on that node's
//     local shard only — the caller is responsible for scatter-gather.
//   - BloomSnapshot returns the latest bloom of IDs durably stored on the
//     responding node. Routers query peer blooms to short-circuit
//     scatter-gather and outright-404 unknown IDs.
//
// Wire types: we keep this intentionally minimal. JSON-friendly fields
// (task payload, result body) travel as bytes/strings — encoding lives
// on the codeq side so we don't bake JSON shape choices into the proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: clusterpb.proto

package clusterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command           string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Payload           []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // raw JSON; codeq parses
	Priority          int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Webhook           string                 `protobuf:"bytes,5,opt,name=webhook,proto3" json:"webhook,omitempty"`
	MaxAttempts       int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Status            string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	LastKnownLocation string                 `protobuf:"bytes,9,opt,name=last_known_location,json=lastKnownLocation,proto3" json:"last_known_location,omitempty"`
	WorkerId          string                 `protobuf:"bytes,10,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LeaseUntil        string                 `protobuf:"bytes,11,opt,name=lease_until,json=leaseUntil,proto3" json:"lease_until,omitempty"` // RFC3339
	Attempts          int32                  `protobuf:"varint,12,opt,name=attempts,proto3" json:"attempts,omitempty"`
	TenantId          string                 `protobuf:"bytes,13,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Error             string                 `protobuf:"bytes,14,opt,name=error,proto3" json:"error,omitempty"`
	ResultKey         string                 `protobuf:"bytes,15,opt,name=result_key,json=resultKey,proto3" json:"result_key,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TraceParent       string                 `protobuf:"bytes,18,opt,name=trace_parent,json=traceParent,proto3" json:"trace_parent,omitempty"`
	TraceState        string                 `protobuf:"bytes,19,opt,name=trace_state,json=traceState,proto3" json:"trace_state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_clusterpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetWebhook() string {
	if x != nil {
		return x.Webhook
	}
	return ""
}

func (x *Task) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Task) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetLastKnownLocation() string {
	if x != nil {
		return x.LastKnownLocation
	}
	return ""
}

func (x *Task) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Task) GetLeaseUntil() string {
	if x != nil {
		return x.LeaseUntil
	}
	return ""
}

func (x *Task) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Task) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Task) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Task) GetResultKey() string {
	if x != nil {
		return x.ResultKey
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Task) GetTraceParent() string {
	if x != nil {
		return x.TraceParent
	}
	return ""
}

func (x *Task) GetTraceState() string {
	if x != nil {
		return x.TraceState
	}
	return ""
}

type ResultRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ResultJson    []byte                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // JSON payload
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Artifacts     []string               `protobuf:"bytes,5,rep,name=artifacts,proto3" json:"artifacts,omitempty"` // each is JSON-encoded ArtifactOut
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRecord) Reset() {
	*x = ResultRecord{}
	mi := &file_clusterpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRecord) ProtoMessage() {}

func (x *ResultRecord) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRecord.ProtoReflect.Descriptor instead.
func (*ResultRecord) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{1}
}

func (x *ResultRecord) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ResultRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResultRecord) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *ResultRecord) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResultRecord) GetArtifacts() []string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ResultRecord) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_clusterpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	NotFound      bool                   `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_clusterpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *GetTaskResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ExtendSeconds int32                  `protobuf:"varint,3,opt,name=extend_seconds,json=extendSeconds,proto3" json:"extend_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_clusterpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetExtendSeconds() int32 {
	if x != nil {
		return x.ExtendSeconds
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotFound      bool                   `protobuf:"varint,1,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	NotOwner      bool                   `protobuf:"varint,2,opt,name=not_owner,json=notOwner,proto3" json:"not_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_clusterpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

func (x *HeartbeatResponse) GetNotOwner() bool {
	if x != nil {
		return x.NotOwner
	}
	return false
}

type AbandonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonRequest) Reset() {
	*x = AbandonRequest{}
	mi := &file_clusterpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonRequest) ProtoMessage() {}

func (x *AbandonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonRequest.ProtoReflect.Descriptor instead.
func (*AbandonRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{6}
}

func (x *AbandonRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AbandonRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type AbandonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotFound      bool                   `protobuf:"varint,1,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	NotOwner      bool                   `protobuf:"varint,2,opt,name=not_owner,json=notOwner,proto3" json:"not_owner,omitempty"`
	NotInProgress bool                   `protobuf:"varint,3,opt,name=not_in_progress,json=notInProgress,proto3" json:"not_in_progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonResponse) Reset() {
	*x = AbandonResponse{}
	mi := &file_clusterpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonResponse) ProtoMessage() {}

func (x *AbandonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonResponse.ProtoReflect.Descriptor instead.
func (*AbandonResponse) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{7}
}

func (x *AbandonResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

func (x *AbandonResponse) GetNotOwner() bool {
	if x != nil {
		return x.NotOwner
	}
	return false
}

func (x *AbandonResponse) GetNotInProgress() bool {
	if x != nil {
		return x.NotInProgress
	}
	return false
}

type NackRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId           string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	DelaySeconds       int32                  `protobuf:"varint,3,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	MaxAttemptsDefault int32                  `protobuf:"varint,4,opt,name=max_attempts_default,json=maxAttemptsDefault,proto3" json:"max_attempts_default,omitempty"`
	Reason             string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_clusterpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{8}
}

func (x *NackRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *NackRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *NackRequest) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *NackRequest) GetMaxAttemptsDefault() int32 {
	if x != nil {
		return x.MaxAttemptsDefault
	}
	return 0
}

func (x *NackRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type NackResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AppliedDelaySeconds int32                  `protobuf:"varint,1,opt,name=applied_delay_seconds,json=appliedDelaySeconds,proto3" json:"applied_delay_seconds,omitempty"`
	Dlq                 bool                   `protobuf:"varint,2,opt,name=dlq,proto3" json:"dlq,omitempty"`
	NotFound            bool                   `protobuf:"varint,3,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	NotOwner            bool                   `protobuf:"varint,4,opt,name=not_owner,json=notOwner,proto3" json:"not_owner,omitempty"`
	NotInProgress       bool                   `protobuf:"varint,5,opt,name=not_in_progress,json=notInProgress,proto3" json:"not_in_progress,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NackResponse) Reset() {
	*x = NackResponse{}
	mi := &file_clusterpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackResponse) ProtoMessage() {}

func (x *NackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackResponse.ProtoReflect.Descriptor instead.
func (*NackResponse) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{9}
}

func (x *NackResponse) GetAppliedDelaySeconds() int32 {
	if x != nil {
		return x.AppliedDelaySeconds
	}
	return 0
}

func (x *NackResponse) GetDlq() bool {
	if x != nil {
		return x.Dlq
	}
	return false
}

func (x *NackResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

func (x *NackResponse) GetNotOwner() bool {
	if x != nil {
		return x.NotOwner
	}
	return false
}

func (x *NackResponse) GetNotInProgress() bool {
	if x != nil {
		return x.NotInProgress
	}
	return false
}

type SaveResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ResultRecord          `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"` // optional hint for direct routing on the inner side
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResultRequest) Reset() {
	*x = SaveResultRequest{}
	mi := &file_clusterpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResultRequest) ProtoMessage() {}

func (x *SaveResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResultRequest.ProtoReflect.Descriptor instead.
func (*SaveResultRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{10}
}

func (x *SaveResultRequest) GetRecord() *ResultRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *SaveResultRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SaveResultRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type SaveResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotFound      bool                   `protobuf:"varint,1,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResultResponse) Reset() {
	*x = SaveResultResponse{}
	mi := &file_clusterpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResultResponse) ProtoMessage() {}

func (x *SaveResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResultResponse.ProtoReflect.Descriptor instead.
func (*SaveResultResponse) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{11}
}

func (x *SaveResultResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

type UpdateOnCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOnCompleteRequest) Reset() {
	*x = UpdateOnCompleteRequest{}
	mi := &file_clusterpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOnCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOnCompleteRequest) ProtoMessage() {}

func (x *UpdateOnCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOnCompleteRequest.ProtoReflect.Descriptor instead.
func (*UpdateOnCompleteRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateOnCompleteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateOnCompleteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *UpdateOnCompleteRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateOnCompleteRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateOnCompleteRequest) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type UpdateOnCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotFound      bool                   `protobuf:"varint,1,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOnCompleteResponse) Reset() {
	*x = UpdateOnCompleteResponse{}
	mi := &file_clusterpb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOnCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOnCompleteResponse) ProtoMessage() {}

func (x *UpdateOnCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOnCompleteResponse.ProtoReflect.Descriptor instead.
func (*UpdateOnCompleteResponse) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateOnCompleteResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

// LocalClaim asks the receiving node to pop from its local Pebble shard
// only — caller (router) is responsible for fanning out across all nodes
// and selecting the first non-empty response.
type LocalClaimRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkerId           string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Commands           []string               `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	LeaseSeconds       int32                  `protobuf:"varint,3,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	InspectLimit       int32                  `protobuf:"varint,4,opt,name=inspect_limit,json=inspectLimit,proto3" json:"inspect_limit,omitempty"`
	MaxAttemptsDefault int32                  `protobuf:"varint,5,opt,name=max_attempts_default,json=maxAttemptsDefault,proto3" json:"max_attempts_default,omitempty"`
	TenantId           string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LocalClaimRequest) Reset() {
	*x = LocalClaimRequest{}
	mi := &file_clusterpb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalClaimRequest) ProtoMessage() {}

func (x *LocalClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalClaimRequest.ProtoReflect.Descriptor instead.
func (*LocalClaimRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{14}
}

func (x *LocalClaimRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *LocalClaimRequest) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *LocalClaimRequest) GetLeaseSeconds() int32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

func (x *LocalClaimRequest) GetInspectLimit() int32 {
	if x != nil {
		return x.InspectLimit
	}
	return 0
}

func (x *LocalClaimRequest) GetMaxAttemptsDefault() int32 {
	if x != nil {
		return x.MaxAttemptsDefault
	}
	return 0
}

func (x *LocalClaimRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type LocalClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Empty         bool                   `protobuf:"varint,2,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalClaimResponse) Reset() {
	*x = LocalClaimResponse{}
	mi := &file_clusterpb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalClaimResponse) ProtoMessage() {}

func (x *LocalClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalClaimResponse.ProtoReflect.Descriptor instead.
func (*LocalClaimResponse) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{15}
}

func (x *LocalClaimResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *LocalClaimResponse) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

type PendingLengthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingLengthRequest) Reset() {
	*x = PendingLengthRequest{}
	mi := &file_clusterpb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingLengthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingLengthRequest) ProtoMessage() {}

func (x *PendingLengthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingLengthRequest.ProtoReflect.Descriptor instead.
func (*PendingLengthRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{16}
}

func (x *PendingLengthRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type PendingLengthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int64                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingLengthResponse) Reset() {
	*x = PendingLengthResponse{}
	mi := &file_clusterpb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingLengthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingLengthResponse) ProtoMessage() {}

func (x *PendingLengthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingLengthResponse.ProtoReflect.Descriptor instead.
func (*PendingLengthResponse) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{17}
}

func (x *PendingLengthResponse) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type QueueStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatsRequest) Reset() {
	*x = QueueStatsRequest{}
	mi := &file_clusterpb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatsRequest) ProtoMessage() {}

func (x *QueueStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatsRequest.ProtoReflect.Descriptor instead.
func (*QueueStatsRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{18}
}

func (x *QueueStatsRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *QueueStatsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type QueueStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         int64                  `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Delayed       int64                  `protobuf:"varint,2,opt,name=delayed,proto3" json:"delayed,omitempty"`
	InProgress    int64                  `protobuf:"varint,3,opt,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"`
	Dlq           int64                  `protobuf:"varint,4,opt,name=dlq,proto3" json:"dlq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatsResponse) Reset() {
	*x = QueueStatsResponse{}
	mi := &file_clusterpb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatsResponse) ProtoMessage() {}

func (x *QueueStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatsResponse.ProtoReflect.Descriptor instead.
func (*QueueStatsResponse) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{19}
}

func (x *QueueStatsResponse) GetReady() int64 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *QueueStatsResponse) GetDelayed() int64 {
	if x != nil {
		return x.Delayed
	}
	return 0
}

func (x *QueueStatsResponse) GetInProgress() int64 {
	if x != nil {
		return x.InProgress
	}
	return 0
}

func (x *QueueStatsResponse) GetDlq() int64 {
	if x != nil {
		return x.Dlq
	}
	return 0
}

type AdminQueuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminQueuesRequest) Reset() {
	*x = AdminQueuesRequest{}
	mi := &file_clusterpb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminQueuesRequest) ProtoMessage() {}

func (x *AdminQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminQueuesRequest.ProtoReflect.Descriptor instead.
func (*AdminQueuesRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{20}
}

type AdminQueuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        map[string]int64       `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminQueuesResponse) Reset() {
	*x = AdminQueuesResponse{}
	mi := &file_clusterpb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminQueuesResponse) ProtoMessage() {}

func (x *AdminQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminQueuesResponse.ProtoReflect.Descriptor instead.
func (*AdminQueuesResponse) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{21}
}

func (x *AdminQueuesResponse) GetCounts() map[string]int64 {
	if x != nil {
		return x.Counts
	}
	return nil
}

// Bloom snapshot transferred between nodes. m_bits is the bloom's bit
// array (raw bytes), num_hashes the configured k, num_items the count of
// items currently inserted, sequence is an incrementing version for
// freshness comparisons.
type BloomSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloomSnapshotRequest) Reset() {
	*x = BloomSnapshotRequest{}
	mi := &file_clusterpb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloomSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloomSnapshotRequest) ProtoMessage() {}

func (x *BloomSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloomSnapshotRequest.ProtoReflect.Descriptor instead.
func (*BloomSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{22}
}

type BloomSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MBits         []byte                 `protobuf:"bytes,1,opt,name=m_bits,json=mBits,proto3" json:"m_bits,omitempty"`
	NumHashes     uint32                 `protobuf:"varint,2,opt,name=num_hashes,json=numHashes,proto3" json:"num_hashes,omitempty"`
	NumItems      uint64                 `protobuf:"varint,3,opt,name=num_items,json=numItems,proto3" json:"num_items,omitempty"`
	Sequence      uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	NodeId        string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloomSnapshotResponse) Reset() {
	*x = BloomSnapshotResponse{}
	mi := &file_clusterpb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloomSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloomSnapshotResponse) ProtoMessage() {}

func (x *BloomSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloomSnapshotResponse.ProtoReflect.Descriptor instead.
func (*BloomSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{23}
}

func (x *BloomSnapshotResponse) GetMBits() []byte {
	if x != nil {
		return x.MBits
	}
	return nil
}

func (x *BloomSnapshotResponse) GetNumHashes() uint32 {
	if x != nil {
		return x.NumHashes
	}
	return 0
}

func (x *BloomSnapshotResponse) GetNumItems() uint64 {
	if x != nil {
		return x.NumItems
	}
	return 0
}

func (x *BloomSnapshotResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *BloomSnapshotResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// EnqueueRequest carries every field the local Enqueue needs, with the
// task ID already chosen by the router so the hash → owner assignment
// is honored when the call lands on a peer.
type EnqueueRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority       int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Webhook        string                 `protobuf:"bytes,5,opt,name=webhook,proto3" json:"webhook,omitempty"`
	MaxAttempts    int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// visible_at_unix=0 means "available immediately" (i.e. not delayed).
	VisibleAtUnix int64  `protobuf:"varint,8,opt,name=visible_at_unix,json=visibleAtUnix,proto3" json:"visible_at_unix,omitempty"`
	TenantId      string `protobuf:"bytes,9,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_clusterpb_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{24}
}

func (x *EnqueueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnqueueRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *EnqueueRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueueRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EnqueueRequest) GetWebhook() string {
	if x != nil {
		return x.Webhook
	}
	return ""
}

func (x *EnqueueRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *EnqueueRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *EnqueueRequest) GetVisibleAtUnix() int64 {
	if x != nil {
		return x.VisibleAtUnix
	}
	return 0
}

func (x *EnqueueRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"` // mirrors EnqueueWithReady's bool return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_clusterpb_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{25}
}

func (x *EnqueueResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *EnqueueResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

var File_clusterpb_proto protoreflect.FileDescriptor

const file_clusterpb_proto_rawDesc = "" +
	"\n" +
	"\x0fclusterpb.proto\x12\tclusterpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x04\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x18\n" +
	"\awebhook\x18\x05 \x01(\tR\awebhook\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12.\n" +
	"\x13last_known_location\x18\t \x01(\tR\x11lastKnownLocation\x12\x1b\n" +
	"\tworker_id\x18\n" +
	" \x01(\tR\bworkerId\x12\x1f\n" +
	"\vlease_until\x18\v \x01(\tR\n" +
	"leaseUntil\x12\x1a\n" +
	"\battempts\x18\f \x01(\x05R\battempts\x12\x1b\n" +
	"\ttenant_id\x18\r \x01(\tR\btenantId\x12\x14\n" +
	"\x05error\x18\x0e \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"result_key\x18\x0f \x01(\tR\tresultKey\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12!\n" +
	"\ftrace_parent\x18\x12 \x01(\tR\vtraceParent\x12\x1f\n" +
	"\vtrace_state\x18\x13 \x01(\tR\n" +
	"traceState\"\xd3\x01\n" +
	"\fResultRecord\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\fR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1c\n" +
	"\tartifacts\x18\x05 \x03(\tR\tartifacts\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x0fGetTaskResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.clusterpb.TaskR\x04task\x12\x1b\n" +
	"\tnot_found\x18\x02 \x01(\bR\bnotFound\"o\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12%\n" +
	"\x0eextend_seconds\x18\x03 \x01(\x05R\rextendSeconds\"M\n" +
	"\x11HeartbeatResponse\x12\x1b\n" +
	"\tnot_found\x18\x01 \x01(\bR\bnotFound\x12\x1b\n" +
	"\tnot_owner\x18\x02 \x01(\bR\bnotOwner\"F\n" +
	"\x0eAbandonRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\"s\n" +
	"\x0fAbandonResponse\x12\x1b\n" +
	"\tnot_found\x18\x01 \x01(\bR\bnotFound\x12\x1b\n" +
	"\tnot_owner\x18\x02 \x01(\bR\bnotOwner\x12&\n" +
	"\x0fnot_in_progress\x18\x03 \x01(\bR\rnotInProgress\"\xb2\x01\n" +
	"\vNackRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12#\n" +
	"\rdelay_seconds\x18\x03 \x01(\x05R\fdelaySeconds\x120\n" +
	"\x14max_attempts_default\x18\x04 \x01(\x05R\x12maxAttemptsDefault\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xb6\x01\n" +
	"\fNackResponse\x122\n" +
	"\x15applied_delay_seconds\x18\x01 \x01(\x05R\x13appliedDelaySeconds\x12\x10\n" +
	"\x03dlq\x18\x02 \x01(\bR\x03dlq\x12\x1b\n" +
	"\tnot_found\x18\x03 \x01(\bR\bnotFound\x12\x1b\n" +
	"\tnot_owner\x18\x04 \x01(\bR\bnotOwner\x12&\n" +
	"\x0fnot_in_progress\x18\x05 \x01(\bR\rnotInProgress\"{\n" +
	"\x11SaveResultRequest\x12/\n" +
	"\x06record\x18\x01 \x01(\v2\x17.clusterpb.ResultRecordR\x06record\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"1\n" +
	"\x12SaveResultResponse\x12\x1b\n" +
	"\tnot_found\x18\x01 \x01(\bR\bnotFound\"\x9e\x01\n" +
	"\x17UpdateOnCompleteRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\"7\n" +
	"\x18UpdateOnCompleteResponse\x12\x1b\n" +
	"\tnot_found\x18\x01 \x01(\bR\bnotFound\"\xe5\x01\n" +
	"\x11LocalClaimRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bcommands\x18\x02 \x03(\tR\bcommands\x12#\n" +
	"\rlease_seconds\x18\x03 \x01(\x05R\fleaseSeconds\x12#\n" +
	"\rinspect_limit\x18\x04 \x01(\x05R\finspectLimit\x120\n" +
	"\x14max_attempts_default\x18\x05 \x01(\x05R\x12maxAttemptsDefault\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"O\n" +
	"\x12LocalClaimResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.clusterpb.TaskR\x04task\x12\x14\n" +
	"\x05empty\x18\x02 \x01(\bR\x05empty\"0\n" +
	"\x14PendingLengthRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"/\n" +
	"\x15PendingLengthResponse\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x03R\x06length\"J\n" +
	"\x11QueueStatsRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"w\n" +
	"\x12QueueStatsResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\x03R\x05ready\x12\x18\n" +
	"\adelayed\x18\x02 \x01(\x03R\adelayed\x12\x1f\n" +
	"\vin_progress\x18\x03 \x01(\x03R\n" +
	"inProgress\x12\x10\n" +
	"\x03dlq\x18\x04 \x01(\x03R\x03dlq\"\x14\n" +
	"\x12AdminQueuesRequest\"\x94\x01\n" +
	"\x13AdminQueuesResponse\x12B\n" +
	"\x06counts\x18\x01 \x03(\v2*.clusterpb.AdminQueuesResponse.CountsEntryR\x06counts\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x16\n" +
	"\x14BloomSnapshotRequest\"\x9f\x01\n" +
	"\x15BloomSnapshotResponse\x12\x15\n" +
	"\x06m_bits\x18\x01 \x01(\fR\x05mBits\x12\x1d\n" +
	"\n" +
	"num_hashes\x18\x02 \x01(\rR\tnumHashes\x12\x1b\n" +
	"\tnum_items\x18\x03 \x01(\x04R\bnumItems\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\"\x9b\x02\n" +
	"\x0eEnqueueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x18\n" +
	"\awebhook\x18\x05 \x01(\tR\awebhook\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12&\n" +
	"\x0fvisible_at_unix\x18\b \x01(\x03R\rvisibleAtUnix\x12\x1b\n" +
	"\ttenant_id\x18\t \x01(\tR\btenantId\"L\n" +
	"\x0fEnqueueResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.clusterpb.TaskR\x04task\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready2\x85\a\n" +
	"\bTaskNode\x12@\n" +
	"\aEnqueue\x12\x19.clusterpb.EnqueueRequest\x1a\x1a.clusterpb.EnqueueResponse\x12@\n" +
	"\aGetTask\x12\x19.clusterpb.GetTaskRequest\x1a\x1a.clusterpb.GetTaskResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.clusterpb.HeartbeatRequest\x1a\x1c.clusterpb.HeartbeatResponse\x12@\n" +
	"\aAbandon\x12\x19.clusterpb.AbandonRequest\x1a\x1a.clusterpb.AbandonResponse\x127\n" +
	"\x04Nack\x12\x16.clusterpb.NackRequest\x1a\x17.clusterpb.NackResponse\x12I\n" +
	"\n" +
	"SaveResult\x12\x1c.clusterpb.SaveResultRequest\x1a\x1d.clusterpb.SaveResultResponse\x12[\n" +
	"\x10UpdateOnComplete\x12\".clusterpb.UpdateOnCompleteRequest\x1a#.clusterpb.UpdateOnCompleteResponse\x12I\n" +
	"\n" +
	"LocalClaim\x12\x1c.clusterpb.LocalClaimRequest\x1a\x1d.clusterpb.LocalClaimResponse\x12R\n" +
	"\rPendingLength\x12\x1f.clusterpb.PendingLengthRequest\x1a .clusterpb.PendingLengthResponse\x12I\n" +
	"\n" +
	"QueueStats\x12\x1c.clusterpb.QueueStatsRequest\x1a\x1d.clusterpb.QueueStatsResponse\x12L\n" +
	"\vAdminQueues\x12\x1d.clusterpb.AdminQueuesRequest\x1a\x1e.clusterpb.AdminQueuesResponse\x12R\n" +
	"\rBloomSnapshot\x12\x1f.clusterpb.BloomSnapshotRequest\x1a .clusterpb.BloomSnapshotResponseB<Z:github.com/osvaldoandrade/codeq/internal/cluster/clusterpbb\x06proto3"

var (
	file_clusterpb_proto_rawDescOnce sync.Once
	file_clusterpb_proto_rawDescData []byte
)

func file_clusterpb_proto_rawDescGZIP() []byte {
	file_clusterpb_proto_rawDescOnce.Do(func() {
		file_clusterpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusterpb_proto_rawDesc), len(file_clusterpb_proto_rawDesc)))
	})
	return file_clusterpb_proto_rawDescData
}

var file_clusterpb_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_clusterpb_proto_goTypes = []any{
	(*Task)(nil),                     // 0: clusterpb.Task
	(*ResultRecord)(nil),             // 1: clusterpb.ResultRecord
	(*GetTaskRequest)(nil),           // 2: clusterpb.GetTaskRequest
	(*GetTaskResponse)(nil),          // 3: clusterpb.GetTaskResponse
	(*HeartbeatRequest)(nil),         // 4: clusterpb.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 5: clusterpb.HeartbeatResponse
	(*AbandonRequest)(nil),           // 6: clusterpb.AbandonRequest
	(*AbandonResponse)(nil),          // 7: clusterpb.AbandonResponse
	(*NackRequest)(nil),              // 8: clusterpb.NackRequest
	(*NackResponse)(nil),             // 9: clusterpb.NackResponse
	(*SaveResultRequest)(nil),        // 10: clusterpb.SaveResultRequest
	(*SaveResultResponse)(nil),       // 11: clusterpb.SaveResultResponse
	(*UpdateOnCompleteRequest)(nil),  // 12: clusterpb.UpdateOnCompleteRequest
	(*UpdateOnCompleteResponse)(nil), // 13: clusterpb.UpdateOnCompleteResponse
	(*LocalClaimRequest)(nil),        // 14: clusterpb.LocalClaimRequest
	(*LocalClaimResponse)(nil),       // 15: clusterpb.LocalClaimResponse
	(*PendingLengthRequest)(nil),     // 16: clusterpb.PendingLengthRequest
	(*PendingLengthResponse)(nil),    // 17: clusterpb.PendingLengthResponse
	(*QueueStatsRequest)(nil),        // 18: clusterpb.QueueStatsRequest
	(*QueueStatsResponse)(nil),       // 19: clusterpb.QueueStatsResponse
	(*AdminQueuesRequest)(nil),       // 20: clusterpb.AdminQueuesRequest
	(*AdminQueuesResponse)(nil),      // 21: clusterpb.AdminQueuesResponse
	(*BloomSnapshotRequest)(nil),     // 22: clusterpb.BloomSnapshotRequest
	(*BloomSnapshotResponse)(nil),    // 23: clusterpb.BloomSnapshotResponse
	(*EnqueueRequest)(nil),           // 24: clusterpb.EnqueueRequest
	(*EnqueueResponse)(nil),          // 25: clusterpb.EnqueueResponse
	nil,                              // 26: clusterpb.AdminQueuesResponse.CountsEntry
	(*timestamppb.Timestamp)(nil),    // 27: google.protobuf.Timestamp
}
var file_clusterpb_proto_depIdxs = []int32{
	27, // 0: clusterpb.Task.created_at:type_name -> google.protobuf.Timestamp
	27, // 1: clusterpb.Task.updated_at:type_name -> google.protobuf.Timestamp
	27, // 2: clusterpb.ResultRecord.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 3: clusterpb.GetTaskResponse.task:type_name -> clusterpb.Task
	1,  // 4: clusterpb.SaveResultRequest.record:type_name -> clusterpb.ResultRecord
	0,  // 5: clusterpb.LocalClaimResponse.task:type_name -> clusterpb.Task
	26, // 6: clusterpb.AdminQueuesResponse.counts:type_name -> clusterpb.AdminQueuesResponse.CountsEntry
	0,  // 7: clusterpb.EnqueueResponse.task:type_name -> clusterpb.Task
	24, // 8: clusterpb.TaskNode.Enqueue:input_type -> clusterpb.EnqueueRequest
	2,  // 9: clusterpb.TaskNode.GetTask:input_type -> clusterpb.GetTaskRequest
	4,  // 10: clusterpb.TaskNode.Heartbeat:input_type -> clusterpb.HeartbeatRequest
	6,  // 11: clusterpb.TaskNode.Abandon:input_type -> clusterpb.AbandonRequest
	8,  // 12: clusterpb.TaskNode.Nack:input_type -> clusterpb.NackRequest
	10, // 13: clusterpb.TaskNode.SaveResult:input_type -> clusterpb.SaveResultRequest
	12, // 14: clusterpb.TaskNode.UpdateOnComplete:input_type -> clusterpb.UpdateOnCompleteRequest
	14, // 15: clusterpb.TaskNode.LocalClaim:input_type -> clusterpb.LocalClaimRequest
	16, // 16: clusterpb.TaskNode.PendingLength:input_type -> clusterpb.PendingLengthRequest
	18, // 17: clusterpb.TaskNode.QueueStats:input_type -> clusterpb.QueueStatsRequest
	20, // 18: clusterpb.TaskNode.AdminQueues:input_type -> clusterpb.AdminQueuesRequest
	22, // 19: clusterpb.TaskNode.BloomSnapshot:input_type -> clusterpb.BloomSnapshotRequest
	25, // 20: clusterpb.TaskNode.Enqueue:output_type -> clusterpb.EnqueueResponse
	3,  // 21: clusterpb.TaskNode.GetTask:output_type -> clusterpb.GetTaskResponse
	5,  // 22: clusterpb.TaskNode.Heartbeat:output_type -> clusterpb.HeartbeatResponse
	7,  // 23: clusterpb.TaskNode.Abandon:output_type -> clusterpb.AbandonResponse
	9,  // 24: clusterpb.TaskNode.Nack:output_type -> clusterpb.NackResponse
	11, // 25: clusterpb.TaskNode.SaveResult:output_type -> clusterpb.SaveResultResponse
	13, // 26: clusterpb.TaskNode.UpdateOnComplete:output_type -> clusterpb.UpdateOnCompleteResponse
	15, // 27: clusterpb.TaskNode.LocalClaim:output_type -> clusterpb.LocalClaimResponse
	17, // 28: clusterpb.TaskNode.PendingLength:output_type -> clusterpb.PendingLengthResponse
	19, // 29: clusterpb.TaskNode.QueueStats:output_type -> clusterpb.QueueStatsResponse
	21, // 30: clusterpb.TaskNode.AdminQueues:output_type -> clusterpb.AdminQueuesResponse
	23, // 31: clusterpb.TaskNode.BloomSnapshot:output_type -> clusterpb.BloomSnapshotResponse
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_clusterpb_proto_init() }
func file_clusterpb_proto_init() {
	if File_clusterpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusterpb_proto_rawDesc), len(file_clusterpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clusterpb_proto_goTypes,
		DependencyIndexes: file_clusterpb_proto_depIdxs,
		MessageInfos:      file_clusterpb_proto_msgTypes,
	}.Build()
	File_clusterpb_proto = out.File
	file_clusterpb_proto_goTypes = nil
	file_clusterpb_proto_depIdxs = nil
}
