// Package producerpb defines the external producer streaming protocol.
//
// Goal: replace the per-call HTTP round-trip on the create hot path
// (POST /v1/codeq/tasks) with a single long-lived bidirectional gRPC
// stream per producer. Auth and tenant resolution happen exactly once
// at stream-open; from then on the producer pushes CreateTask events
// with a monotonically-increasing seq, and the server acks each one
// with the assigned task id once durable.
//
// Pipeline-friendly: the protocol is fully async — a producer may have
// N requests in flight before the first ack arrives. The seq lets the
// producer correlate acks back to its own requests without round-tripping.
// Phase 3 of the throughput refactor relies on this to lift the
// producer-side ceiling above the ~33k creates/s the REST path tops out
// at.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: producerpb.proto

package producerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hello is the FIRST message a producer MUST send on a freshly-opened
// stream. The server validates the bearer token, resolves the tenant,
// and replies with HelloAck. Subsequent CreateTask messages inherit
// the resolved tenant — they cannot override it.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_producerpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_producerpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_producerpb_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// CreateTask is one task submission. seq is producer-assigned and must
// be strictly monotonically increasing per stream; the server echoes
// it on the matching CreateAck so the producer can pair them up.
//
// run_at and delay_seconds mirror the REST API: at most one should be
// set; if both are absent the task is immediately claimable.
type CreateTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Seq            uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // opaque JSON, server-side stored as-is
	Priority       int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Webhook        string                 `protobuf:"bytes,5,opt,name=webhook,proto3" json:"webhook,omitempty"`
	MaxAttempts    int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	RunAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"`
	DelaySeconds   int32                  `protobuf:"varint,9,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	TraceParent    string                 `protobuf:"bytes,10,opt,name=trace_parent,json=traceParent,proto3" json:"trace_parent,omitempty"` // W3C trace context (optional)
	TraceState     string                 `protobuf:"bytes,11,opt,name=trace_state,json=traceState,proto3" json:"trace_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTask) Reset() {
	*x = CreateTask{}
	mi := &file_producerpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTask) ProtoMessage() {}

func (x *CreateTask) ProtoReflect() protoreflect.Message {
	mi := &file_producerpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTask.ProtoReflect.Descriptor instead.
func (*CreateTask) Descriptor() ([]byte, []int) {
	return file_producerpb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTask) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CreateTask) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateTask) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateTask) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateTask) GetWebhook() string {
	if x != nil {
		return x.Webhook
	}
	return ""
}

func (x *CreateTask) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *CreateTask) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateTask) GetRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RunAt
	}
	return nil
}

func (x *CreateTask) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *CreateTask) GetTraceParent() string {
	if x != nil {
		return x.TraceParent
	}
	return ""
}

func (x *CreateTask) GetTraceState() string {
	if x != nil {
		return x.TraceState
	}
	return ""
}

// CreateTaskBatch is a producer pipelining N CreateTasks into a single
// stream message. Server processes them with one fan-out goroutine
// instead of one per CreateTask, and emits a single CreateAckBatch
// covering every seq. The Pebble commit coalescer (Phase 1.1) merges
// the resulting writes into fewer commits; combined with the reduced
// gRPC framing this is the Phase 6 / Q3 batch path for producers.
type CreateTaskBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*CreateTask          `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskBatch) Reset() {
	*x = CreateTaskBatch{}
	mi := &file_producerpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskBatch) ProtoMessage() {}

func (x *CreateTaskBatch) ProtoReflect() protoreflect.Message {
	mi := &file_producerpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskBatch.ProtoReflect.Descriptor instead.
func (*CreateTaskBatch) Descriptor() ([]byte, []int) {
	return file_producerpb_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskBatch) GetTasks() []*CreateTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ProducerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ProducerEvent_Hello
	//	*ProducerEvent_Create
	//	*ProducerEvent_CreateBatch
	Event         isProducerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducerEvent) Reset() {
	*x = ProducerEvent{}
	mi := &file_producerpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerEvent) ProtoMessage() {}

func (x *ProducerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_producerpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerEvent.ProtoReflect.Descriptor instead.
func (*ProducerEvent) Descriptor() ([]byte, []int) {
	return file_producerpb_proto_rawDescGZIP(), []int{3}
}

func (x *ProducerEvent) GetEvent() isProducerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ProducerEvent) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Event.(*ProducerEvent_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ProducerEvent) GetCreate() *CreateTask {
	if x != nil {
		if x, ok := x.Event.(*ProducerEvent_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *ProducerEvent) GetCreateBatch() *CreateTaskBatch {
	if x != nil {
		if x, ok := x.Event.(*ProducerEvent_CreateBatch); ok {
			return x.CreateBatch
		}
	}
	return nil
}

type isProducerEvent_Event interface {
	isProducerEvent_Event()
}

type ProducerEvent_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ProducerEvent_Create struct {
	Create *CreateTask `protobuf:"bytes,2,opt,name=create,proto3,oneof"`
}

type ProducerEvent_CreateBatch struct {
	CreateBatch *CreateTaskBatch `protobuf:"bytes,3,opt,name=create_batch,json=createBatch,proto3,oneof"`
}

func (*ProducerEvent_Hello) isProducerEvent_Event() {}

func (*ProducerEvent_Create) isProducerEvent_Event() {}

func (*ProducerEvent_CreateBatch) isProducerEvent_Event() {}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_producerpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_producerpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_producerpb_proto_rawDescGZIP(), []int{4}
}

func (x *HelloAck) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *HelloAck) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

// CreateAck pairs with the CreateTask whose seq matches. ok=false means
// the create was rejected; error_message has the reason. task_id is the
// server-assigned id (mirrors REST 202 response).
type CreateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAck) Reset() {
	*x = CreateAck{}
	mi := &file_producerpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAck) ProtoMessage() {}

func (x *CreateAck) ProtoReflect() protoreflect.Message {
	mi := &file_producerpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAck.ProtoReflect.Descriptor instead.
func (*CreateAck) Descriptor() ([]byte, []int) {
	return file_producerpb_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAck) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CreateAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateAck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ServerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerError) Reset() {
	*x = ServerError{}
	mi := &file_producerpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerError) ProtoMessage() {}

func (x *ServerError) ProtoReflect() protoreflect.Message {
	mi := &file_producerpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerError.ProtoReflect.Descriptor instead.
func (*ServerError) Descriptor() ([]byte, []int) {
	return file_producerpb_proto_rawDescGZIP(), []int{6}
}

func (x *ServerError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ServerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CreateAckBatch acks every CreateTask in a CreateTaskBatch in one
// message. Order matches the input order.
type CreateAckBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acks          []*CreateAck           `protobuf:"bytes,1,rep,name=acks,proto3" json:"acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAckBatch) Reset() {
	*x = CreateAckBatch{}
	mi := &file_producerpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAckBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAckBatch) ProtoMessage() {}

func (x *CreateAckBatch) ProtoReflect() protoreflect.Message {
	mi := &file_producerpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAckBatch.ProtoReflect.Descriptor instead.
func (*CreateAckBatch) Descriptor() ([]byte, []int) {
	return file_producerpb_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAckBatch) GetAcks() []*CreateAck {
	if x != nil {
		return x.Acks
	}
	return nil
}

type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_HelloAck
	//	*ServerEvent_CreateAck
	//	*ServerEvent_Error
	//	*ServerEvent_CreateAckBatch
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_producerpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_producerpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_producerpb_proto_rawDescGZIP(), []int{8}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ServerEvent) GetCreateAck() *CreateAck {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_CreateAck); ok {
			return x.CreateAck
		}
	}
	return nil
}

func (x *ServerEvent) GetError() *ServerError {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerEvent) GetCreateAckBatch() *CreateAckBatch {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_CreateAckBatch); ok {
			return x.CreateAckBatch
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ServerEvent_CreateAck struct {
	CreateAck *CreateAck `protobuf:"bytes,2,opt,name=create_ack,json=createAck,proto3,oneof"`
}

type ServerEvent_Error struct {
	Error *ServerError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ServerEvent_CreateAckBatch struct {
	CreateAckBatch *CreateAckBatch `protobuf:"bytes,4,opt,name=create_ack_batch,json=createAckBatch,proto3,oneof"`
}

func (*ServerEvent_HelloAck) isServerEvent_Event() {}

func (*ServerEvent_CreateAck) isServerEvent_Event() {}

func (*ServerEvent_Error) isServerEvent_Event() {}

func (*ServerEvent_CreateAckBatch) isServerEvent_Event() {}

var File_producerpb_proto protoreflect.FileDescriptor

const file_producerpb_proto_rawDesc = "" +
	"\n" +
	"\x10producerpb.proto\x12\n" +
	"producerpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1d\n" +
	"\x05Hello\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xf0\x02\n" +
	"\n" +
	"CreateTask\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x18\n" +
	"\awebhook\x18\x05 \x01(\tR\awebhook\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x121\n" +
	"\x06run_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x05runAt\x12#\n" +
	"\rdelay_seconds\x18\t \x01(\x05R\fdelaySeconds\x12!\n" +
	"\ftrace_parent\x18\n" +
	" \x01(\tR\vtraceParent\x12\x1f\n" +
	"\vtrace_state\x18\v \x01(\tR\n" +
	"traceState\"?\n" +
	"\x0fCreateTaskBatch\x12,\n" +
	"\x05tasks\x18\x01 \x03(\v2\x16.producerpb.CreateTaskR\x05tasks\"\xb7\x01\n" +
	"\rProducerEvent\x12)\n" +
	"\x05hello\x18\x01 \x01(\v2\x11.producerpb.HelloH\x00R\x05hello\x120\n" +
	"\x06create\x18\x02 \x01(\v2\x16.producerpb.CreateTaskH\x00R\x06create\x12@\n" +
	"\fcreate_batch\x18\x03 \x01(\v2\x1b.producerpb.CreateTaskBatchH\x00R\vcreateBatchB\a\n" +
	"\x05event\"A\n" +
	"\bHelloAck\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\"k\n" +
	"\tCreateAck\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\";\n" +
	"\vServerError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x0eCreateAckBatch\x12)\n" +
	"\x04acks\x18\x01 \x03(\v2\x15.producerpb.CreateAckR\x04acks\"\xfc\x01\n" +
	"\vServerEvent\x123\n" +
	"\thello_ack\x18\x01 \x01(\v2\x14.producerpb.HelloAckH\x00R\bhelloAck\x126\n" +
	"\n" +
	"create_ack\x18\x02 \x01(\v2\x15.producerpb.CreateAckH\x00R\tcreateAck\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x17.producerpb.ServerErrorH\x00R\x05error\x12F\n" +
	"\x10create_ack_batch\x18\x04 \x01(\v2\x1a.producerpb.CreateAckBatchH\x00R\x0ecreateAckBatchB\a\n" +
	"\x05event2R\n" +
	"\x0eProducerStream\x12@\n" +
	"\x06Stream\x12\x19.producerpb.ProducerEvent\x1a\x17.producerpb.ServerEvent(\x010\x01B>Z<github.com/osvaldoandrade/codeq/internal/producer/producerpbb\x06proto3"

var (
	file_producerpb_proto_rawDescOnce sync.Once
	file_producerpb_proto_rawDescData []byte
)

func file_producerpb_proto_rawDescGZIP() []byte {
	file_producerpb_proto_rawDescOnce.Do(func() {
		file_producerpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_producerpb_proto_rawDesc), len(file_producerpb_proto_rawDesc)))
	})
	return file_producerpb_proto_rawDescData
}

var file_producerpb_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_producerpb_proto_goTypes = []any{
	(*Hello)(nil),                 // 0: producerpb.Hello
	(*CreateTask)(nil),            // 1: producerpb.CreateTask
	(*CreateTaskBatch)(nil),       // 2: producerpb.CreateTaskBatch
	(*ProducerEvent)(nil),         // 3: producerpb.ProducerEvent
	(*HelloAck)(nil),              // 4: producerpb.HelloAck
	(*CreateAck)(nil),             // 5: producerpb.CreateAck
	(*ServerError)(nil),           // 6: producerpb.ServerError
	(*CreateAckBatch)(nil),        // 7: producerpb.CreateAckBatch
	(*ServerEvent)(nil),           // 8: producerpb.ServerEvent
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_producerpb_proto_depIdxs = []int32{
	9,  // 0: producerpb.CreateTask.run_at:type_name -> google.protobuf.Timestamp
	1,  // 1: producerpb.CreateTaskBatch.tasks:type_name -> producerpb.CreateTask
	0,  // 2: producerpb.ProducerEvent.hello:type_name -> producerpb.Hello
	1,  // 3: producerpb.ProducerEvent.create:type_name -> producerpb.CreateTask
	2,  // 4: producerpb.ProducerEvent.create_batch:type_name -> producerpb.CreateTaskBatch
	5,  // 5: producerpb.CreateAckBatch.acks:type_name -> producerpb.CreateAck
	4,  // 6: producerpb.ServerEvent.hello_ack:type_name -> producerpb.HelloAck
	5,  // 7: producerpb.ServerEvent.create_ack:type_name -> producerpb.CreateAck
	6,  // 8: producerpb.ServerEvent.error:type_name -> producerpb.ServerError
	7,  // 9: producerpb.ServerEvent.create_ack_batch:type_name -> producerpb.CreateAckBatch
	3,  // 10: producerpb.ProducerStream.Stream:input_type -> producerpb.ProducerEvent
	8,  // 11: producerpb.ProducerStream.Stream:output_type -> producerpb.ServerEvent
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_producerpb_proto_init() }
func file_producerpb_proto_init() {
	if File_producerpb_proto != nil {
		return
	}
	file_producerpb_proto_msgTypes[3].OneofWrappers = []any{
		(*ProducerEvent_Hello)(nil),
		(*ProducerEvent_Create)(nil),
		(*ProducerEvent_CreateBatch)(nil),
	}
	file_producerpb_proto_msgTypes[8].OneofWrappers = []any{
		(*ServerEvent_HelloAck)(nil),
		(*ServerEvent_CreateAck)(nil),
		(*ServerEvent_Error)(nil),
		(*ServerEvent_CreateAckBatch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_producerpb_proto_rawDesc), len(file_producerpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_producerpb_proto_goTypes,
		DependencyIndexes: file_producerpb_proto_depIdxs,
		MessageInfos:      file_producerpb_proto_msgTypes,
	}.Build()
	File_producerpb_proto = out.File
	file_producerpb_proto_goTypes = nil
	file_producerpb_proto_depIdxs = nil
}
