// Package producerpb defines the external producer streaming protocol.
//
// Goal: replace the per-call HTTP round-trip on the create hot path
// (POST /v1/codeq/tasks) with a single long-lived bidirectional gRPC
// stream per producer. Auth and tenant resolution happen exactly once
// at stream-open; from then on the producer pushes CreateTask events
// with a monotonically-increasing seq, and the server acks each one
// with the assigned task id once durable.
//
// Pipeline-friendly: the protocol is fully async — a producer may have
// N requests in flight before the first ack arrives. The seq lets the
// producer correlate acks back to its own requests without round-tripping.
// Phase 3 of the throughput refactor relies on this to lift the
// producer-side ceiling above the ~33k creates/s the REST path tops out
// at.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: producerpb.proto

package producerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProducerStream_Stream_FullMethodName = "/producerpb.ProducerStream/Stream"
)

// ProducerStreamClient is the client API for ProducerStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProducerStreamClient interface {
	// Stream is the single long-lived bidirectional channel. The producer
	// opens it, sends Hello, then pipelines CreateTask events. The server
	// acks asynchronously — acks may arrive out of order relative to send
	// order under high concurrency, but the seq always pairs them with
	// the originating request.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProducerEvent, ServerEvent], error)
}

type producerStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewProducerStreamClient(cc grpc.ClientConnInterface) ProducerStreamClient {
	return &producerStreamClient{cc}
}

func (c *producerStreamClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProducerEvent, ServerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProducerStream_ServiceDesc.Streams[0], ProducerStream_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProducerEvent, ServerEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProducerStream_StreamClient = grpc.BidiStreamingClient[ProducerEvent, ServerEvent]

// ProducerStreamServer is the server API for ProducerStream service.
// All implementations must embed UnimplementedProducerStreamServer
// for forward compatibility.
type ProducerStreamServer interface {
	// Stream is the single long-lived bidirectional channel. The producer
	// opens it, sends Hello, then pipelines CreateTask events. The server
	// acks asynchronously — acks may arrive out of order relative to send
	// order under high concurrency, but the seq always pairs them with
	// the originating request.
	Stream(grpc.BidiStreamingServer[ProducerEvent, ServerEvent]) error
	mustEmbedUnimplementedProducerStreamServer()
}

// UnimplementedProducerStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProducerStreamServer struct{}

func (UnimplementedProducerStreamServer) Stream(grpc.BidiStreamingServer[ProducerEvent, ServerEvent]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedProducerStreamServer) mustEmbedUnimplementedProducerStreamServer() {}
func (UnimplementedProducerStreamServer) testEmbeddedByValue()                        {}

// UnsafeProducerStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProducerStreamServer will
// result in compilation errors.
type UnsafeProducerStreamServer interface {
	mustEmbedUnimplementedProducerStreamServer()
}

func RegisterProducerStreamServer(s grpc.ServiceRegistrar, srv ProducerStreamServer) {
	// If the following call panics, it indicates UnimplementedProducerStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProducerStream_ServiceDesc, srv)
}

func _ProducerStream_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProducerStreamServer).Stream(&grpc.GenericServerStream[ProducerEvent, ServerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProducerStream_StreamServer = grpc.BidiStreamingServer[ProducerEvent, ServerEvent]

// ProducerStream_ServiceDesc is the grpc.ServiceDesc for ProducerStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProducerStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "producerpb.ProducerStream",
	HandlerType: (*ProducerStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _ProducerStream_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "producerpb.proto",
}
