// Package workerpb defines the external worker streaming protocol.
//
// Goal: replace the per-call HTTP round-trip on the claim+result hot
// path (one POST /claim → one POST /tasks/<id>/result per task) with a
// single long-lived bidirectional gRPC stream per worker. Auth and
// tenant resolution happen exactly once at stream-open; from then on
// the worker pushes Ready/Result/Nack/Abandon/Heartbeat events and the
// server pushes Task assignments down the same connection.
//
// The producer side (POST /tasks) is unchanged — only the worker hot
// path is converted, because that's the call pattern that runs in
// tight loops and dominates the request-rate ceiling per Phase 1 bench.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workerpb.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Webhook       string                 `protobuf:"bytes,5,opt,name=webhook,proto3" json:"webhook,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	WorkerId      string                 `protobuf:"bytes,8,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LeaseUntil    string                 `protobuf:"bytes,9,opt,name=lease_until,json=leaseUntil,proto3" json:"lease_until,omitempty"`
	Attempts      int32                  `protobuf:"varint,10,opt,name=attempts,proto3" json:"attempts,omitempty"`
	TenantId      string                 `protobuf:"bytes,11,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_workerpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetWebhook() string {
	if x != nil {
		return x.Webhook
	}
	return ""
}

func (x *Task) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Task) GetLeaseUntil() string {
	if x != nil {
		return x.LeaseUntil
	}
	return ""
}

func (x *Task) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Task) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Hello is the FIRST message a worker MUST send on a freshly-opened
// stream. The server validates the bearer token, resolves tenant +
// scopes, and replies with HelloAck. If auth fails the server closes
// the stream with an Unauthenticated status.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Token string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// worker_id identifies this worker for the purposes of lease ownership.
	// If empty the server falls back to the JWT subject claim.
	WorkerId      string `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_workerpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Hello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// Ready is the worker saying "I have capacity for one more task with
// any of these commands; push me one when available." Each Ready
// consumes up to `count` Tasks; the server responds with either:
//   - one TaskAssignment per task (count==0 or 1; legacy path), or
//   - one TaskBatch carrying up to count tasks (count > 1; Phase 6 / Q2).
//
// When count==0 the server defaults to 1 for backward compatibility
// with clients that never set the field.
type Ready struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Commands     []string               `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	LeaseSeconds int32                  `protobuf:"varint,2,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	// count = max tasks to deliver in response. 0/1 = single TaskAssignment.
	// >1 = TaskBatch capped at count. Server may deliver fewer than count
	// if the queue empties before the batch fills.
	Count         int32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_workerpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{2}
}

func (x *Ready) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Ready) GetLeaseSeconds() int32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

func (x *Ready) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Result is the worker submitting completion for a previously-assigned
// task. The server applies it and may respond with a ResultAck. Status
// is one of COMPLETED / FAILED — the proto uses the same string values
// as the REST API for parity.
type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ResultJson    []byte                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // present when status=COMPLETED
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                             // present when status=FAILED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_workerpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{3}
}

func (x *Result) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Result) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Result) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Nack returns the task to the queue with a delay before it becomes
// claimable again. delay_seconds=0 means "immediately re-claimable".
type Nack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	DelaySeconds  int32                  `protobuf:"varint,2,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nack) Reset() {
	*x = Nack{}
	mi := &file_workerpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nack) ProtoMessage() {}

func (x *Nack) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nack.ProtoReflect.Descriptor instead.
func (*Nack) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{4}
}

func (x *Nack) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Nack) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *Nack) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Heartbeat extends the worker's lease on a task it's still processing.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExtendSeconds int32                  `protobuf:"varint,2,opt,name=extend_seconds,json=extendSeconds,proto3" json:"extend_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_workerpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Heartbeat) GetExtendSeconds() int32 {
	if x != nil {
		return x.ExtendSeconds
	}
	return 0
}

// Abandon releases the lease without nacking — task goes straight back
// to pending. Used when the worker shuts down cleanly.
type Abandon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Abandon) Reset() {
	*x = Abandon{}
	mi := &file_workerpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Abandon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Abandon) ProtoMessage() {}

func (x *Abandon) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Abandon.ProtoReflect.Descriptor instead.
func (*Abandon) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{6}
}

func (x *Abandon) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// ResultBatch is the worker submitting completion for N tasks in a
// single message. Equivalent to N Result events but the server
// processes them with one BatchSubmit call (single Pebble batch +
// single round-trip of acks), eliminating the per-task Send overhead
// and amortising claim/result write paths. Phase 6 / Q2.
type ResultBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Result              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultBatch) Reset() {
	*x = ResultBatch{}
	mi := &file_workerpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultBatch) ProtoMessage() {}

func (x *ResultBatch) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultBatch.ProtoReflect.Descriptor instead.
func (*ResultBatch) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{7}
}

func (x *ResultBatch) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type WorkerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*WorkerEvent_Hello
	//	*WorkerEvent_Ready
	//	*WorkerEvent_Result
	//	*WorkerEvent_Nack
	//	*WorkerEvent_Heartbeat
	//	*WorkerEvent_Abandon
	//	*WorkerEvent_ResultBatch
	Event         isWorkerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerEvent) Reset() {
	*x = WorkerEvent{}
	mi := &file_workerpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerEvent) ProtoMessage() {}

func (x *WorkerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerEvent.ProtoReflect.Descriptor instead.
func (*WorkerEvent) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{8}
}

func (x *WorkerEvent) GetEvent() isWorkerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WorkerEvent) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerEvent) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *WorkerEvent) GetResult() *Result {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *WorkerEvent) GetNack() *Nack {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Nack); ok {
			return x.Nack
		}
	}
	return nil
}

func (x *WorkerEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerEvent) GetAbandon() *Abandon {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Abandon); ok {
			return x.Abandon
		}
	}
	return nil
}

func (x *WorkerEvent) GetResultBatch() *ResultBatch {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_ResultBatch); ok {
			return x.ResultBatch
		}
	}
	return nil
}

type isWorkerEvent_Event interface {
	isWorkerEvent_Event()
}

type WorkerEvent_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerEvent_Ready struct {
	Ready *Ready `protobuf:"bytes,2,opt,name=ready,proto3,oneof"`
}

type WorkerEvent_Result struct {
	Result *Result `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type WorkerEvent_Nack struct {
	Nack *Nack `protobuf:"bytes,4,opt,name=nack,proto3,oneof"`
}

type WorkerEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,5,opt,name=heartbeat,proto3,oneof"`
}

type WorkerEvent_Abandon struct {
	Abandon *Abandon `protobuf:"bytes,6,opt,name=abandon,proto3,oneof"`
}

type WorkerEvent_ResultBatch struct {
	ResultBatch *ResultBatch `protobuf:"bytes,7,opt,name=result_batch,json=resultBatch,proto3,oneof"`
}

func (*WorkerEvent_Hello) isWorkerEvent_Event() {}

func (*WorkerEvent_Ready) isWorkerEvent_Event() {}

func (*WorkerEvent_Result) isWorkerEvent_Event() {}

func (*WorkerEvent_Nack) isWorkerEvent_Event() {}

func (*WorkerEvent_Heartbeat) isWorkerEvent_Event() {}

func (*WorkerEvent_Abandon) isWorkerEvent_Event() {}

func (*WorkerEvent_ResultBatch) isWorkerEvent_Event() {}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_workerpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{9}
}

func (x *HelloAck) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HelloAck) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// TaskAssignment is sent exactly once per Ready (one-to-one pairing).
// If no task is available the server holds the Ready until one is.
type TaskAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_workerpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{10}
}

func (x *TaskAssignment) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// TaskBatch is the server's response to a Ready with count > 1.
// Carries up to Ready.count Tasks in a single message. May be shorter
// than count if the queue emptied; an empty TaskBatch is a legal
// no-tasks-available response.
type TaskBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskBatch) Reset() {
	*x = TaskBatch{}
	mi := &file_workerpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskBatch) ProtoMessage() {}

func (x *TaskBatch) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskBatch.ProtoReflect.Descriptor instead.
func (*TaskBatch) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{11}
}

func (x *TaskBatch) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// ResultAckBatch acknowledges all results in a ResultBatch in one
// message. Order matches the ResultBatch.results order.
type ResultAckBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acks          []*ResultAck           `protobuf:"bytes,1,rep,name=acks,proto3" json:"acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultAckBatch) Reset() {
	*x = ResultAckBatch{}
	mi := &file_workerpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultAckBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultAckBatch) ProtoMessage() {}

func (x *ResultAckBatch) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultAckBatch.ProtoReflect.Descriptor instead.
func (*ResultAckBatch) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{12}
}

func (x *ResultAckBatch) GetAcks() []*ResultAck {
	if x != nil {
		return x.Acks
	}
	return nil
}

type ResultAck struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// ok=false means the submission was rejected; error_message has the
	// reason (not-found / not-owner / not-in-progress).
	Ok            bool   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultAck) Reset() {
	*x = ResultAck{}
	mi := &file_workerpb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultAck) ProtoMessage() {}

func (x *ResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultAck.ProtoReflect.Descriptor instead.
func (*ResultAck) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{13}
}

func (x *ResultAck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ResultAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ResultAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_workerpb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{14}
}

func (x *HeartbeatAck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HeartbeatAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type NackAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TaskId              string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Ok                  bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AppliedDelaySeconds int32                  `protobuf:"varint,4,opt,name=applied_delay_seconds,json=appliedDelaySeconds,proto3" json:"applied_delay_seconds,omitempty"`
	Dlq                 bool                   `protobuf:"varint,5,opt,name=dlq,proto3" json:"dlq,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NackAck) Reset() {
	*x = NackAck{}
	mi := &file_workerpb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackAck) ProtoMessage() {}

func (x *NackAck) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackAck.ProtoReflect.Descriptor instead.
func (*NackAck) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{15}
}

func (x *NackAck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *NackAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NackAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *NackAck) GetAppliedDelaySeconds() int32 {
	if x != nil {
		return x.AppliedDelaySeconds
	}
	return 0
}

func (x *NackAck) GetDlq() bool {
	if x != nil {
		return x.Dlq
	}
	return false
}

type AbandonAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonAck) Reset() {
	*x = AbandonAck{}
	mi := &file_workerpb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonAck) ProtoMessage() {}

func (x *AbandonAck) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonAck.ProtoReflect.Descriptor instead.
func (*AbandonAck) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{16}
}

func (x *AbandonAck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AbandonAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AbandonAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ServerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerError) Reset() {
	*x = ServerError{}
	mi := &file_workerpb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerError) ProtoMessage() {}

func (x *ServerError) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerError.ProtoReflect.Descriptor instead.
func (*ServerError) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{17}
}

func (x *ServerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_HelloAck
	//	*ServerEvent_Task
	//	*ServerEvent_ResultAck
	//	*ServerEvent_HeartbeatAck
	//	*ServerEvent_NackAck
	//	*ServerEvent_AbandonAck
	//	*ServerEvent_Error
	//	*ServerEvent_TaskBatch
	//	*ServerEvent_ResultAckBatch
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_workerpb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_workerpb_proto_rawDescGZIP(), []int{18}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ServerEvent) GetTask() *TaskAssignment {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *ServerEvent) GetResultAck() *ResultAck {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_ResultAck); ok {
			return x.ResultAck
		}
	}
	return nil
}

func (x *ServerEvent) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ServerEvent) GetNackAck() *NackAck {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_NackAck); ok {
			return x.NackAck
		}
	}
	return nil
}

func (x *ServerEvent) GetAbandonAck() *AbandonAck {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_AbandonAck); ok {
			return x.AbandonAck
		}
	}
	return nil
}

func (x *ServerEvent) GetError() *ServerError {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerEvent) GetTaskBatch() *TaskBatch {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_TaskBatch); ok {
			return x.TaskBatch
		}
	}
	return nil
}

func (x *ServerEvent) GetResultAckBatch() *ResultAckBatch {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_ResultAckBatch); ok {
			return x.ResultAckBatch
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ServerEvent_Task struct {
	Task *TaskAssignment `protobuf:"bytes,2,opt,name=task,proto3,oneof"`
}

type ServerEvent_ResultAck struct {
	ResultAck *ResultAck `protobuf:"bytes,3,opt,name=result_ack,json=resultAck,proto3,oneof"`
}

type ServerEvent_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,4,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ServerEvent_NackAck struct {
	NackAck *NackAck `protobuf:"bytes,5,opt,name=nack_ack,json=nackAck,proto3,oneof"`
}

type ServerEvent_AbandonAck struct {
	AbandonAck *AbandonAck `protobuf:"bytes,6,opt,name=abandon_ack,json=abandonAck,proto3,oneof"`
}

type ServerEvent_Error struct {
	Error *ServerError `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

type ServerEvent_TaskBatch struct {
	TaskBatch *TaskBatch `protobuf:"bytes,8,opt,name=task_batch,json=taskBatch,proto3,oneof"`
}

type ServerEvent_ResultAckBatch struct {
	ResultAckBatch *ResultAckBatch `protobuf:"bytes,9,opt,name=result_ack_batch,json=resultAckBatch,proto3,oneof"`
}

func (*ServerEvent_HelloAck) isServerEvent_Event() {}

func (*ServerEvent_Task) isServerEvent_Event() {}

func (*ServerEvent_ResultAck) isServerEvent_Event() {}

func (*ServerEvent_HeartbeatAck) isServerEvent_Event() {}

func (*ServerEvent_NackAck) isServerEvent_Event() {}

func (*ServerEvent_AbandonAck) isServerEvent_Event() {}

func (*ServerEvent_Error) isServerEvent_Event() {}

func (*ServerEvent_TaskBatch) isServerEvent_Event() {}

func (*ServerEvent_ResultAckBatch) isServerEvent_Event() {}

var File_workerpb_proto protoreflect.FileDescriptor

const file_workerpb_proto_rawDesc = "" +
	"\n" +
	"\x0eworkerpb.proto\x12\bworkerpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x18\n" +
	"\awebhook\x18\x05 \x01(\tR\awebhook\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1b\n" +
	"\tworker_id\x18\b \x01(\tR\bworkerId\x12\x1f\n" +
	"\vlease_until\x18\t \x01(\tR\n" +
	"leaseUntil\x12\x1a\n" +
	"\battempts\x18\n" +
	" \x01(\x05R\battempts\x12\x1b\n" +
	"\ttenant_id\x18\v \x01(\tR\btenantId\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\":\n" +
	"\x05Hello\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\"^\n" +
	"\x05Ready\x12\x1a\n" +
	"\bcommands\x18\x01 \x03(\tR\bcommands\x12#\n" +
	"\rlease_seconds\x18\x02 \x01(\x05R\fleaseSeconds\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"p\n" +
	"\x06Result\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\fR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\\\n" +
	"\x04Nack\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12#\n" +
	"\rdelay_seconds\x18\x02 \x01(\x05R\fdelaySeconds\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"K\n" +
	"\tHeartbeat\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x0eextend_seconds\x18\x02 \x01(\x05R\rextendSeconds\"\"\n" +
	"\aAbandon\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"9\n" +
	"\vResultBatch\x12*\n" +
	"\aresults\x18\x01 \x03(\v2\x10.workerpb.ResultR\aresults\"\xda\x02\n" +
	"\vWorkerEvent\x12'\n" +
	"\x05hello\x18\x01 \x01(\v2\x0f.workerpb.HelloH\x00R\x05hello\x12'\n" +
	"\x05ready\x18\x02 \x01(\v2\x0f.workerpb.ReadyH\x00R\x05ready\x12*\n" +
	"\x06result\x18\x03 \x01(\v2\x10.workerpb.ResultH\x00R\x06result\x12$\n" +
	"\x04nack\x18\x04 \x01(\v2\x0e.workerpb.NackH\x00R\x04nack\x123\n" +
	"\theartbeat\x18\x05 \x01(\v2\x13.workerpb.HeartbeatH\x00R\theartbeat\x12-\n" +
	"\aabandon\x18\x06 \x01(\v2\x11.workerpb.AbandonH\x00R\aabandon\x12:\n" +
	"\fresult_batch\x18\a \x01(\v2\x15.workerpb.ResultBatchH\x00R\vresultBatchB\a\n" +
	"\x05event\"D\n" +
	"\bHelloAck\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"4\n" +
	"\x0eTaskAssignment\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.workerpb.TaskR\x04task\"1\n" +
	"\tTaskBatch\x12$\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0e.workerpb.TaskR\x05tasks\"9\n" +
	"\x0eResultAckBatch\x12'\n" +
	"\x04acks\x18\x01 \x03(\v2\x13.workerpb.ResultAckR\x04acks\"Y\n" +
	"\tResultAck\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\\\n" +
	"\fHeartbeatAck\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x9d\x01\n" +
	"\aNackAck\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x122\n" +
	"\x15applied_delay_seconds\x18\x04 \x01(\x05R\x13appliedDelaySeconds\x12\x10\n" +
	"\x03dlq\x18\x05 \x01(\bR\x03dlq\"Z\n" +
	"\n" +
	"AbandonAck\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\";\n" +
	"\vServerError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x82\x04\n" +
	"\vServerEvent\x121\n" +
	"\thello_ack\x18\x01 \x01(\v2\x12.workerpb.HelloAckH\x00R\bhelloAck\x12.\n" +
	"\x04task\x18\x02 \x01(\v2\x18.workerpb.TaskAssignmentH\x00R\x04task\x124\n" +
	"\n" +
	"result_ack\x18\x03 \x01(\v2\x13.workerpb.ResultAckH\x00R\tresultAck\x12=\n" +
	"\rheartbeat_ack\x18\x04 \x01(\v2\x16.workerpb.HeartbeatAckH\x00R\fheartbeatAck\x12.\n" +
	"\bnack_ack\x18\x05 \x01(\v2\x11.workerpb.NackAckH\x00R\anackAck\x127\n" +
	"\vabandon_ack\x18\x06 \x01(\v2\x14.workerpb.AbandonAckH\x00R\n" +
	"abandonAck\x12-\n" +
	"\x05error\x18\a \x01(\v2\x15.workerpb.ServerErrorH\x00R\x05error\x124\n" +
	"\n" +
	"task_batch\x18\b \x01(\v2\x13.workerpb.TaskBatchH\x00R\ttaskBatch\x12D\n" +
	"\x10result_ack_batch\x18\t \x01(\v2\x18.workerpb.ResultAckBatchH\x00R\x0eresultAckBatchB\a\n" +
	"\x05event2J\n" +
	"\fWorkerStream\x12:\n" +
	"\x06Stream\x12\x15.workerpb.WorkerEvent\x1a\x15.workerpb.ServerEvent(\x010\x01B:Z8github.com/osvaldoandrade/codeq/internal/worker/workerpbb\x06proto3"

var (
	file_workerpb_proto_rawDescOnce sync.Once
	file_workerpb_proto_rawDescData []byte
)

func file_workerpb_proto_rawDescGZIP() []byte {
	file_workerpb_proto_rawDescOnce.Do(func() {
		file_workerpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workerpb_proto_rawDesc), len(file_workerpb_proto_rawDesc)))
	})
	return file_workerpb_proto_rawDescData
}

var file_workerpb_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_workerpb_proto_goTypes = []any{
	(*Task)(nil),                  // 0: workerpb.Task
	(*Hello)(nil),                 // 1: workerpb.Hello
	(*Ready)(nil),                 // 2: workerpb.Ready
	(*Result)(nil),                // 3: workerpb.Result
	(*Nack)(nil),                  // 4: workerpb.Nack
	(*Heartbeat)(nil),             // 5: workerpb.Heartbeat
	(*Abandon)(nil),               // 6: workerpb.Abandon
	(*ResultBatch)(nil),           // 7: workerpb.ResultBatch
	(*WorkerEvent)(nil),           // 8: workerpb.WorkerEvent
	(*HelloAck)(nil),              // 9: workerpb.HelloAck
	(*TaskAssignment)(nil),        // 10: workerpb.TaskAssignment
	(*TaskBatch)(nil),             // 11: workerpb.TaskBatch
	(*ResultAckBatch)(nil),        // 12: workerpb.ResultAckBatch
	(*ResultAck)(nil),             // 13: workerpb.ResultAck
	(*HeartbeatAck)(nil),          // 14: workerpb.HeartbeatAck
	(*NackAck)(nil),               // 15: workerpb.NackAck
	(*AbandonAck)(nil),            // 16: workerpb.AbandonAck
	(*ServerError)(nil),           // 17: workerpb.ServerError
	(*ServerEvent)(nil),           // 18: workerpb.ServerEvent
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_workerpb_proto_depIdxs = []int32{
	19, // 0: workerpb.Task.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: workerpb.Task.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 2: workerpb.ResultBatch.results:type_name -> workerpb.Result
	1,  // 3: workerpb.WorkerEvent.hello:type_name -> workerpb.Hello
	2,  // 4: workerpb.WorkerEvent.ready:type_name -> workerpb.Ready
	3,  // 5: workerpb.WorkerEvent.result:type_name -> workerpb.Result
	4,  // 6: workerpb.WorkerEvent.nack:type_name -> workerpb.Nack
	5,  // 7: workerpb.WorkerEvent.heartbeat:type_name -> workerpb.Heartbeat
	6,  // 8: workerpb.WorkerEvent.abandon:type_name -> workerpb.Abandon
	7,  // 9: workerpb.WorkerEvent.result_batch:type_name -> workerpb.ResultBatch
	0,  // 10: workerpb.TaskAssignment.task:type_name -> workerpb.Task
	0,  // 11: workerpb.TaskBatch.tasks:type_name -> workerpb.Task
	13, // 12: workerpb.ResultAckBatch.acks:type_name -> workerpb.ResultAck
	9,  // 13: workerpb.ServerEvent.hello_ack:type_name -> workerpb.HelloAck
	10, // 14: workerpb.ServerEvent.task:type_name -> workerpb.TaskAssignment
	13, // 15: workerpb.ServerEvent.result_ack:type_name -> workerpb.ResultAck
	14, // 16: workerpb.ServerEvent.heartbeat_ack:type_name -> workerpb.HeartbeatAck
	15, // 17: workerpb.ServerEvent.nack_ack:type_name -> workerpb.NackAck
	16, // 18: workerpb.ServerEvent.abandon_ack:type_name -> workerpb.AbandonAck
	17, // 19: workerpb.ServerEvent.error:type_name -> workerpb.ServerError
	11, // 20: workerpb.ServerEvent.task_batch:type_name -> workerpb.TaskBatch
	12, // 21: workerpb.ServerEvent.result_ack_batch:type_name -> workerpb.ResultAckBatch
	8,  // 22: workerpb.WorkerStream.Stream:input_type -> workerpb.WorkerEvent
	18, // 23: workerpb.WorkerStream.Stream:output_type -> workerpb.ServerEvent
	23, // [23:24] is the sub-list for method output_type
	22, // [22:23] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_workerpb_proto_init() }
func file_workerpb_proto_init() {
	if File_workerpb_proto != nil {
		return
	}
	file_workerpb_proto_msgTypes[8].OneofWrappers = []any{
		(*WorkerEvent_Hello)(nil),
		(*WorkerEvent_Ready)(nil),
		(*WorkerEvent_Result)(nil),
		(*WorkerEvent_Nack)(nil),
		(*WorkerEvent_Heartbeat)(nil),
		(*WorkerEvent_Abandon)(nil),
		(*WorkerEvent_ResultBatch)(nil),
	}
	file_workerpb_proto_msgTypes[18].OneofWrappers = []any{
		(*ServerEvent_HelloAck)(nil),
		(*ServerEvent_Task)(nil),
		(*ServerEvent_ResultAck)(nil),
		(*ServerEvent_HeartbeatAck)(nil),
		(*ServerEvent_NackAck)(nil),
		(*ServerEvent_AbandonAck)(nil),
		(*ServerEvent_Error)(nil),
		(*ServerEvent_TaskBatch)(nil),
		(*ServerEvent_ResultAckBatch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workerpb_proto_rawDesc), len(file_workerpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workerpb_proto_goTypes,
		DependencyIndexes: file_workerpb_proto_depIdxs,
		MessageInfos:      file_workerpb_proto_msgTypes,
	}.Build()
	File_workerpb_proto = out.File
	file_workerpb_proto_goTypes = nil
	file_workerpb_proto_depIdxs = nil
}
