// Package workerpb defines the external worker streaming protocol.
//
// Goal: replace the per-call HTTP round-trip on the claim+result hot
// path (one POST /claim → one POST /tasks/<id>/result per task) with a
// single long-lived bidirectional gRPC stream per worker. Auth and
// tenant resolution happen exactly once at stream-open; from then on
// the worker pushes Ready/Result/Nack/Abandon/Heartbeat events and the
// server pushes Task assignments down the same connection.
//
// The producer side (POST /tasks) is unchanged — only the worker hot
// path is converted, because that's the call pattern that runs in
// tight loops and dominates the request-rate ceiling per Phase 1 bench.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: workerpb.proto

package workerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerStream_Stream_FullMethodName = "/workerpb.WorkerStream/Stream"
)

// WorkerStreamClient is the client API for WorkerStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerStreamClient interface {
	// Stream is the single long-lived bidirectional channel. The worker
	// opens it, sends Hello, then loops: send Ready → receive Task →
	// process → send Result. Multiple Readys can be in flight (the worker
	// is free to pipeline). The server keeps each Ready in an internal
	// queue and pairs it with the next claim that wins.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerEvent, ServerEvent], error)
}

type workerStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerStreamClient(cc grpc.ClientConnInterface) WorkerStreamClient {
	return &workerStreamClient{cc}
}

func (c *workerStreamClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerEvent, ServerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerStream_ServiceDesc.Streams[0], WorkerStream_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerEvent, ServerEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerStream_StreamClient = grpc.BidiStreamingClient[WorkerEvent, ServerEvent]

// WorkerStreamServer is the server API for WorkerStream service.
// All implementations must embed UnimplementedWorkerStreamServer
// for forward compatibility.
type WorkerStreamServer interface {
	// Stream is the single long-lived bidirectional channel. The worker
	// opens it, sends Hello, then loops: send Ready → receive Task →
	// process → send Result. Multiple Readys can be in flight (the worker
	// is free to pipeline). The server keeps each Ready in an internal
	// queue and pairs it with the next claim that wins.
	Stream(grpc.BidiStreamingServer[WorkerEvent, ServerEvent]) error
	mustEmbedUnimplementedWorkerStreamServer()
}

// UnimplementedWorkerStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerStreamServer struct{}

func (UnimplementedWorkerStreamServer) Stream(grpc.BidiStreamingServer[WorkerEvent, ServerEvent]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedWorkerStreamServer) mustEmbedUnimplementedWorkerStreamServer() {}
func (UnimplementedWorkerStreamServer) testEmbeddedByValue()                      {}

// UnsafeWorkerStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerStreamServer will
// result in compilation errors.
type UnsafeWorkerStreamServer interface {
	mustEmbedUnimplementedWorkerStreamServer()
}

func RegisterWorkerStreamServer(s grpc.ServiceRegistrar, srv WorkerStreamServer) {
	// If the following call panics, it indicates UnimplementedWorkerStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerStream_ServiceDesc, srv)
}

func _WorkerStream_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerStreamServer).Stream(&grpc.GenericServerStream[WorkerEvent, ServerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerStream_StreamServer = grpc.BidiStreamingServer[WorkerEvent, ServerEvent]

// WorkerStream_ServiceDesc is the grpc.ServiceDesc for WorkerStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workerpb.WorkerStream",
	HandlerType: (*WorkerStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _WorkerStream_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "workerpb.proto",
}
